# Generated by Django 3.0 on 2020-01-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('dob', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(null=True)),
                ('atk', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('id_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Player')),
                ('id_poke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon')),
                ('id_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.PokemonTeam')),
            ],
        ),
    ]
