# Generated by Django 3.0.3 on 2020-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='double_damage_to',
            field=models.ManyToManyField(related_name='_type_double_damage_to_+', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='half_damage_from',
            field=models.ManyToManyField(related_name='_type_half_damage_from_+', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='half_damage_to',
            field=models.ManyToManyField(related_name='_type_half_damage_to_+', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='no_damage_from',
            field=models.ManyToManyField(related_name='_type_no_damage_from_+', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='no_damage_to',
            field=models.ManyToManyField(related_name='_type_no_damage_to_+', to='pokemon.Type'),
        ),
    ]
