# Generated by Django 3.0.3 on 2020-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20200207_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(null=True)),
                ('types', models.ManyToManyField(to='pokemon.Type')),
            ],
        ),
    ]
