# Generated by Django 3.0.3 on 2020-02-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_move_name'),
        ('pokemon', '0003_zone'),
    ]

    operations = [
    ]
