# Generated by Django 3.0.3 on 2020-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_merge_20200207_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='current_hp',
            field=models.IntegerField(null=True),
        ),
    ]
