# Generated by Django 3.0.3 on 2020-02-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_pokemon_current_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Object')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='objects_list',
            field=models.ManyToManyField(through='pokemon.Inventory', to='pokemon.Object'),
        ),
    ]
