# Generated by Django 3.0.2 on 2020-02-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20200207_2005'),
        ('pokemon', '0009_auto_20200207_1958'),
    ]

    operations = [
    ]
